//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> studentid { get; set; }
        public byte[] extractedfeatures { get; set; }
    }
}
